### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by sesispla** [docarys/docarys#3]
Current implementation do not allow users to add plug-ins or extensions to the system. There are many functionalities, but not configurable.

Ideally, the system should allow the configuration of these plugins through docarys.yml:

```yml
site_name: docarys
theme: material
plugins:
    markdown:
         - emoji
         - highlight
    git:
         - enabled: true
         - contributors: true
         - footer_node: false
```
